name: 'Update Changed Projects'
description: 'Configure AWS credentials, install pipeline package, and run update-changes'
inputs:
  pr_number:
    description: 'PR Number (leave empty for main branch)'
    required: false
    default: ''
  starter_projects_key:
    description: 'SSH key for starter projects repository'
    required: true
  github_token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      shell: bash
      run: |
        OIDC_TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value')
        
        CREDENTIALS=$(aws sts assume-role-with-web-identity \
          --role-arn arn:aws:iam::236695143472:role/GitHubAction-AssumeRoleWithAction \
          --role-session-name "github-actions-${{ github.run_id }}" \
          --web-identity-token "$OIDC_TOKEN" \
          --duration-seconds 3600 \
          --query 'Credentials' \
          --output json)
        
        echo "AWS_ACCESS_KEY_ID=$(echo $CREDENTIALS | jq -r '.AccessKeyId')" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=$(echo $CREDENTIALS | jq -r '.SecretAccessKey')" >> $GITHUB_ENV
        echo "AWS_SESSION_TOKEN=$(echo $CREDENTIALS | jq -r '.SessionToken')" >> $GITHUB_ENV
        echo "AWS_DEFAULT_REGION=eu-central-1" >> $GITHUB_ENV

    - name: Install Pipeline Package
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.starter_projects_key }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts
        pip install git+ssh://git@bitbucket.org/imagimob/_starter-projects-pipeline.git

    - name: Start Pipeline
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        if [ "${{ github.event_name }}" == "pull_request_target" ]; then
          PR_NUMBER="${{ github.event.pull_request.number }}"
        elif [ "${{ github.event_name }}" == "pull_request_review" ]; then
          PR_NUMBER="${{ github.event.pull_request.number }}"
        elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          PR_NUMBER="${{ github.event.inputs.pr_number }}"
        else
          # Assume this is a push to main
          PR_NUMBER=""
        fi
        update-changes --pr-number "$PR_NUMBER"
